apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddscore
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: ddscore-pod
        image: local/ddscore:v1
        ports:
        - containerPort: 8888