apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddscore
  labels:
    app: dds_l
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dds_l
  template:
    metadata:
      labels:
        app: dds_l
    spec:
      containers:
      - name: ddscore-pod
        image: local/ddscore:v1
        ports:
        - containerPort: 8888

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: px4
  labels:
    app: px4_l
spec:
  replicas: 4
  selector:
    matchLabels:
      app: px4_l
  template:
    metadata:
      labels:
        app: px4_l
    spec:
      containers:
      - name: px4-pod
        image: local/px4:v1
        ports:
        - containerPort: 8888