apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddscore
  labels:
    app: dds_l
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dds_l
  template:
    metadata:
      labels:
        app: dds_l
    spec:
      containers:
      - name: ddscore-pod
        image: local/ddscore:v1
        # ports: #It seems there is no need for ports rn
        # - containerPort: 8888
        envFrom:
          - configMapRef:
              name: fastdds-config-domain-0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: px4
  labels:
    app: px4_l
spec:
  replicas: 1
  selector:
    matchLabels:
      app: px4_l
  template:
    metadata:
      labels:
        app: px4_l
    spec:
      containers:
      - name: px4-pod
        image: local/px4:v1
        # ports: #It seems there is no need for ports rn
        # - containerPort: 8888
        envFrom:
          - configMapRef:
              name: fastdds-config-domain-0-px4
      #   volumeMounts: #Experiments to work with Gazebo GUI (currently not working)
      #   - mountPath: /tmp/.X11-unix
      #     name: xserver
      #   env:
      #   - name: DISPLAY
      #     value: ":1"
      # volumes:
      # - name: xserver
      #   hostPath:
      #     path: /tmp/.X11-unix
      #     type: Directory # host should have this always