apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mosquitto
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
  - hosts:
    - mqtt.example.com
    secretName: mosquitto-certs
  rules:
  - host: mqtt.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mosquitto-mqtts
            port: 
              number: 1883
  # containers:
  # - args:
  #   - /nginx-ingress-controller
  #   - --publish-service=$(POD_NAMESPACE)/ingress-nginx-controller
  #   - --election-id=ingress-nginx-leader
  #   - --controller-class=k8s.io/ingress-nginx
  #   - --ingress-class=nginx
  #   - --configmap=$(POD_NAMESPACE)/ingress-nginx-controller
  #   - --validating-webhook=:8443
  #   - --validating-webhook-certificate=/usr/local/certificates/cert
  #   - --validating-webhook-key=/usr/local/certificates/key
  #   # Add this
  #   - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
  # ports:
  # - name: mqtts
  #   port: 1883
  #   protocol: TCP
  #   targetPort: 1883
  # - appProtocol: http
  #   name: http
  #   port: 80
  #   protocol: TCP
  #   targetPort: http
  # - appProtocol: https
  #   name: https
  #   port: 443
  #   protocol: TCP
  #   targetPort: https
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0.18
        ports:
        - containerPort: 1883
        - containerPort: 9001
        volumeMounts:
        - mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
          name: config
        - mountPath: /mosquitto/certs/
          name: certs
      volumes:
      - name: config
        configMap:
          name: mosquitto-config
      - name: certs
        secret:
          secretName: mosquitto-certs

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    # DO NOT USE IN PRODUCTION
    allow_anonymous true

    # MQTT with TLS (MQTTS)
    listener 8883
    protocol mqtt

    # Fetch the generated certificates
    cafile /etc/ssl/certs/ca-certificates.crt
    keyfile /mosquitto/certs/tls.key
    certfile /mosquitto/certs/tls.crt

---

apiVersion: v1
kind: Service
metadata:
  name: mosquitto-mqtts
spec:
  type: ClusterIP
  selector:
    app: mosquitto  
  ports:
  - port: 1883

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
data:
  1883: "mqtt://localhost:1883"