apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drn-0
  template:
    metadata:
      labels:
        app: drn-0
    spec:
      containers:
      - name: ddscore
        image: local/ddscore:v1
        ports:
        - containerPort: 1883
        envFrom:
          - configMapRef:
              name: fastdds-config-domain-0
      - name: px4
        image: local/px4:v1
        envFrom:
          - configMapRef:
              name: fastdds-config-domain-0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drn-1
  template:
    metadata:
      labels:
        app: drn-1
    spec:
      containers:
      - name: ddscore
        image: local/ddscore:v1
        ports:
        - containerPort: 1883
        envFrom:
          - configMapRef:
              name: fastdds-config-domain-1
      - name: px4
        image: local/px4:v1
        envFrom:
          - configMapRef:
              name: fastdds-config-domain-1

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mosquitto
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mosquitto
#   template:
#     metadata:
#       labels:
#         app: mosquitto
#     spec:
#       hostNetwork: true
#       containers:
#         - name: mosquitto
#           image: eclipse-mosquitto:2.0.18